default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: apice_backend_development

test:
  <<: *default
  database: apice_backend_test

production:
  <<: *default
  database: apice_backend_production
  username: apice_backend
  password: <%= ENV["APICE_BACKEND_DATABASE_PASSWORD"] %>
